// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzcowhkwaandjalwaxlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y293aGt3YWFuZGphbHdheGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjE4MTYsImV4cCI6MjA2NTY5NzgxNn0.62KtVuQoiUh9bXx83RhSHhhyUhwRQMB9llxldrNQEqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);